stages: 
  - build
  - deploy

build-petclinic:
  stage: build
  script:
    - echo "ðŸ”§ Building Petclinic with Maven..."
    - mvn clean package

deploy-to-tomcat:
  stage: deploy
  script:
    - echo "ðŸš€ Deploying to Tomcat..."
    - mvn tomcat9:deploy
    - echo "âœ… Done deploying"
  environment: production

